### ISSUE TITLE
Request for Code Release of ICON

### ISSUE THREAD

**Issue by zhaoyx-bjyx** [wjhou/ICon#1]
Hi，Your methodology aligns closely with my research goals, and I am very eager to delve deeper into your approach. To this end, I would like to kindly request if you could make the implementation code of your paper available. Thank you very much for your time and for the valuable contributions your work has made to the field. Looking forward to your positive response.

**Comment by wjhou** [comment]
Hi, 

Thank you for your attention. This paper is currently undergoing a revision and I am recently quite busy working on several projects.

I'll try to upload codes for Stage 1 next week. The major part of the method is quite simple and straightforward. I suggest you implement the method yourself if you feel urgent in adopting the models.

Best,
Ethan

**Comment by wjhou** [comment]
Hi @zhaoyx-bjyx 

Sorry for taking so long to release the codes.

I've uploaded part of the codes for reference. However, these codes are copied directly from the original code base and I have not tested them yet. You may not be able to run them successfully.

I will update the repo as soon as possible. Please be patient. 

If you have any questions or concerns, please comment again.

Best,
Ethan
